export const LISTEN_TO_CURRENT_USER_PROFILE = 'LISTEN_TO_CURRENT_USER_PROFILE'
export const LISTEN_TO_SELECTED_USER_PROFILE = 'LIST_TO_SELECTED_USER_PROFILE'
export const LISTEN_TO_USER_PHOTO = 'LISTEN_TO_USER_PHOTO'
export const LIST_TO_USER_EVENT = 'LIST_TO_USER_EVENT'